### ISSUE TITLE
Build fails on windows with java.lang.NoClassDefFoundError: IllegalName

### ISSUE THREAD

**Issue by ecriss** [dzwicker/st-js-gradle-plugin#3]
This is happeng because of:

https://github.com/dzwicker/st-js-gradle-plugin/blob/master/src/main/java/com/github/dzwicker/stjs/gradle/GenerateStJsTask.java#L335

It's trying to replace '/' with a '.' but in windows the File.separatorChar is a backslash so the slash is never replaced.

**Comment by dzwicker** [comment]
This should be fixed. Can you check this?
