### ISSUE TITLE
Build 3.2.2 is not available on Maven Central

### ISSUE THREAD

**Issue by mbaron** [dzwicker/st-js-gradle-plugin#5]
There is a new build available, however, it is not available on MavenCentral repository.
https://github.com/dzwicker/st-js-gradle-plugin/releases/tag/3.2.2

Would you mind to upload artifact to Maven Central?

**Comment by dzwicker** [comment]
Sorry. Missed to release the staging repository to the maven central. Should be online in the next 24h.
